const WEB_SOCKET_ERRORS_HANDLER = 'wsUtils/errorHandler';

const SUBSCRIBE_TASK_CREATION = "task/subscribeCreation"
const UNSUBSCRIBE_TASK_CREATION = "task/unsubscribeCreation"

const SUBSCRIBE_TO_ALL_CREATED_TASKS = "task/subscribeToAllCreated"
const UNSUBSCRIBE_FROM_ALL_CREATED_TASKS = "task/unsubscribeToAllCreated"

const SUBSCRIBE_TO_SHIFT_EVENTS = "shiftEvents/subscribe"
const UNSUBSCRIBE_FROM_SHIFT_EVENTS = "shiftEvents/unsubscribe"

const SUBSCRIBE_TO_ADDED_EMPLOYEE = "employee/subscribeToAddedEmployee"
const UNSUBSCRIBE_FROM_ADDED_EMPLOYEE = "employee/unsubscribeFromAddedEmployee"

const SUBSCRIBE_TO_TASK_EVENTS = "taskEvents/subscribe"
const UNSUBSCRIBE_FROM_TASK_EVENTS = "taskEvents/unsubscribe"

export {
  WEB_SOCKET_ERRORS_HANDLER,
  SUBSCRIBE_TASK_CREATION,
  UNSUBSCRIBE_TASK_CREATION,
  SUBSCRIBE_TO_ALL_CREATED_TASKS,
  UNSUBSCRIBE_FROM_ALL_CREATED_TASKS,
  SUBSCRIBE_TO_SHIFT_EVENTS,
  UNSUBSCRIBE_FROM_SHIFT_EVENTS,
  SUBSCRIBE_TO_ADDED_EMPLOYEE,
  UNSUBSCRIBE_FROM_ADDED_EMPLOYEE,
  SUBSCRIBE_TO_TASK_EVENTS,
  UNSUBSCRIBE_FROM_TASK_EVENTS
};
